export const foodList = [
  { id: "fd_1", name: "Arepa", type: "Food", quantity: 42 },
  { id: "fd_2", name: "Bandeja Paisa", type: "Food", quantity: 18 },
  { id: "fd_3", name: "Ajiaco", type: "Food", quantity: 75 },
  { id: "fd_4", name: "Empanadas", type: "Food", quantity: 33 },
  { id: "fd_5", name: "Buñuelos", type: "Food", quantity: 89 },
  { id: "fd_6", name: "Patacones", type: "Food", quantity: 56 },
  { id: "fd_7", name: "Lechona", type: "Food", quantity: 21 },
  { id: "fd_8", name: "Sancocho", type: "Food", quantity: 67 },
  { id: "fd_9", name: "Ceviche", type: "Food", quantity: 9 },
  { id: "fd_10", name: "Tamales", type: "Food", quantity: 45 },
  { id: "fd_11", name: "Cabro Santandereano", type: "Food", quantity: 12 },
  { id: "fd_12", name: "Chicharrón", type: "Food", quantity: 51 },
  { id: "fd_13", name: "Pan de Bono", type: "Food", quantity: 84 },
  { id: "fd_14", name: "Arepas de Huevo", type: "Food", quantity: 27 },
  { id: "fd_15", name: "Posta Negra", type: "Food", quantity: 60 },
  { id: "fd_16", name: "Chorizo", type: "Food", quantity: 3 },
  { id: "fd_17", name: "Aborrajados", type: "Food", quantity: 39 },
  { id: "fd_18", name: "Arroz con Pollo", type: "Food", quantity: 72 },
  { id: "fd_19", name: "Bocadillo", type: "Food", quantity: 15 },
  { id: "fd_20", name: "Arepas con Hogao", type: "Food", quantity: 54 },
  { id: "drk_1", name: "Tinto", type: "Drink", quantity: 81 },
  { id: "drk_2", name: "Aguardiente", type: "Drink", quantity: 24 },
  { id: "drk_3", name: "Chocolate Santafereño", type: "Drink", quantity: 63 },
  { id: "drk_4", name: "Canelazo", type: "Drink", quantity: 96 },
  { id: "drk_5", name: "Agua de Panela", type: "Drink", quantity: 30 },
  { id: "drk_6", name: "Jugos", type: "Drink", quantity: 69 },
  { id: "drk_7", name: "Kumis", type: "Drink", quantity: 6 },
  { id: "drk_8", name: "Limonada de Coco", type: "Drink", quantity: 36 },
  { id: "drk_9", name: "Piña (Pineapple)", type: "Drink", quantity: 10 },
  { id: "drk_10", name: "Coco Loco", type: "Drink", quantity: 18 },
  { id: "drk_11", name: "Lulo", type: "Drink", quantity: 16 },
  { id: "drk_12", name: "Guanábana", type: "Drink", quantity: 30 },
  { id: "drk_13", name: "Sabajón", type: "Drink", quantity: 78 },
  { id: "drk_14", name: "Mora (Blackberry)", type: "Drink", quantity: 56 },
  { id: "drk_15", name: "Fresa (Strawberry)", type: "Drink", quantity: 67 },
  {
    id: "drk_16",
    name: "Gulupa (Purple Passion Fruit)",
    type: "Drink",
    quantity: 34,
  },
  { id: "drk_17", name: "Mango", type: "Drink", quantity: 11 },
  {
    id: "drk_18",
    name: "Tomate de Árbol (Tree Tomato)",
    type: "Drink",
    quantity: 43,
  },
  { id: "drk_19", name: "Patilla (Watermelon)", type: "Drink", quantity: 13 },
  {
    id: "drk_20",
    name: "Maracuya (Passion Fruit)",
    type: "Drink",
    quantity: 17,
  },
];

// export const foodList = [
//   { id: "fd_1", name: "Arepa", type: "Food", quantity: 42 },
// ];
